### ISSUE TITLE
Not able to convert ndjson to json in Linux using cucumber standalone json-formatter

### ISSUE THREAD

**Issue by surajwaitz** [cucumber/json-formatter#26]

**Comment by fgaliazzo** [comment]
Same here in production... any news? solutions?
Architecture: x86_64
Downloaded FIle : cucumber-json-formatter-linux-amd64

**Comment by mpkorstanje** [comment]
Cucumber is a mostly unfunded Open Source project and runs largely on peoples spare time.

But we are generally happy to accept pull requests. So if you have a pressing problem that must be resolved in a timely fashion, you can investigate and provide a fix yourself.

**Comment by fgaliazzo** [comment]
I'm just trying to help, but I don't have enough knowledge. i tried apt-get -y install golang-go, now i have this error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c2f23]
goroutine 1 [running]:
math/rand.(*rngSource).Seed(0xc0000756c8, 0x40d647)
	/opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rng.go:226 +0x143
math/rand.NewSource(...)
	/opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:45
math/rand.init()
	/opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:293 +0x34
An error was thrown in your plugins file while executing the handler for the after:run event.

**Comment by jvanhent** [comment]
> sorry for the previous post. I recently migrated a project from cypress-cucumber-preprocessor to @badeball/cypress-cucumber-preprocessor.
> 
> I'm just trying to help, but I don't have enough knowledge. i tried apt-get -y install golang-go, now i have this error:
> 
> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c2f23] goroutine 1 [running]: math/rand.(*rngSource).Seed(0xc0000756c8, 0x40d647) /opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rng.go:226 +0x143 math/rand.NewSource(...) /opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:45 math/rand.init() /opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:293 +0x34 An error was thrown in your plugins file while executing the handler for the after:run event.

Same issue as fgaliazzo here

**Comment by vvanmol** [comment]
I'm also facing the same issue as @fgaliazzo and @jvanhent 

In my case I'm building a Docker Image where I set up `cucumber-json-formatter`.  And after downloading the binary to a PATH location I run the command `cucumber-json-formatter --help` which displays the expected message.

But then if I instantiate a Docker Container from that Docker Image, and within that Container I run the same `cucumber-json-formatter --help` I don't get the same expected message as during the Docker build but I get instead:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c2f23]

goroutine 1 [running]:
math/rand.(*rngSource).Seed(0xc00004b6c8, 0x40d647)
	/opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rng.go:226 +0x143
math/rand.NewSource(...)
	/opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:45
math/rand.init()
	/opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:293 +0x34
```

This Docker scenario involves architecture `amd64` which leads to the issue.  I've run the same scenario from a Mac M1 with architecture `arm64` and there I could not reproduce the issue...
