### ISSUE TITLE
Getting `TypeError: JSON.parse(...).map is not a function`

### ISSUE THREAD

**Issue by rakeshnambiar** [cucumber/json-formatter#35]
### 👓 TypeError: JSON.parse(...).map is not a function

```
> report
> node ./cypress/generate-reports/report.mjs

~/GitHub/browserify-esm/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:36
            JSON.parse(data).map(json => {
                             ^

TypeError: JSON.parse(...).map is not a function
    at ~/GitHub/browserify-esm/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:36:30
    at Array.map (<anonymous>)
    at collectJSONS (~/GitHub/browserify-esm/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:30:15)
    at Object.generateReport [as generate] (~/GitHub/browserify-esm/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:78:23)
    at file://~/GitHub/browserify-esm/cypress/generate-reports/report.mjs:4:8
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v19.2.0
```

### ✅ What did you expect to see?

I would expect the html reports are generated successfully from the JSON file.

### 📦 Which tool/library version are you using?

Latest version of preprocessor

### 🔬 How could we reproduce it?

1. Clone and use the project https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/browserify-esm
2. Set up the https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md#json-reports
3. Generate the JSON report by running `npx cypress run` command
4. Create a JS file and copy the contents from https://github.com/wswebcreation/multiple-cucumber-html-reporter
5. Adjust the path/directory and run this JS file

Alternatively you can clone the repository:
https://github.com/rakeshnambiar/cypress-bdd-cucumber

**Comment by rakeshnambiar** [comment]
this is working after I moved the JSON files to a separate directory
