### ISSUE TITLE
Panic error while running json formatter inside docker container

### ISSUE THREAD

**Issue by ssdshaikh** [cucumber/json-formatter#52]
Getting panic error when executing the standalone cucumber-json-formatter inside docker container.
Using version 19.0.0 (cucumber-json-formatter-linux-amd64)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c2f23]

goroutine 1 [running]:
math/rand.(*rngSource).Seed(0xc0000416c8, 0x40d647)
 /opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rng.go:226 +0x143
math/rand.NewSource(...)
 /opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:45
math/rand.init()
 /opt/hostedtoolcache/go/1.17.10/x64/src/math/rand/rand.go:293 +0x34

**Comment by chezsmithy** [comment]
Could this be related to a upx bug?
